import assert from 'assert';

import fileSystem from 'fs';

import {describe, it} from 'mocha';

describe('css-module-flow-loader test', () => {
    it('Main test', () => {
        // eslint-disable-next-line no-sync
        const actualResult = fileSystem.readFileSync('./test/fixture/fixture.scss.flow').toString();

        const expectedResult = `// @flow strict
/* This file is automatically generated by css-module-flow-loader */
declare module.exports: {|
    +'connected_class': string;
    +'inner_usual_class': string;
    +'usual_class': string;
|};
`;

        assert(actualResult === expectedResult);
    });
});
